
package br.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import br.interfaces.MessageRMI;
import br.interfaces.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISoapServices", targetNamespace = "http://interfaces.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISoapServices {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.interfaces.MessageRMI
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://interfaces.br/ISoapServices/consultaLivroRequest", output = "http://interfaces.br/ISoapServices/consultaLivroResponse")
    public MessageRMI consultaLivro(
        @WebParam(name = "arg0", partName = "arg0")
        MessageRMI arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.interfaces.MessageRMI
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://interfaces.br/ISoapServices/reservaLivrosRequest", output = "http://interfaces.br/ISoapServices/reservaLivrosResponse")
    public MessageRMI reservaLivros(
        @WebParam(name = "arg0", partName = "arg0")
        MessageRMI arg0);

}
